export interface Product {
  slug: string;
  name: string;
  category: "men" | "women";
  price: number;
  priceUSD: number;
  description: string;
  shortDescription: string;
  images: string[];
  sizes: number[];
  colors: { name: string; hex: string }[];
  style: string;
  material: string;
  artisan: string;
  artisanLocation: string;
  artisanImage: string;
  rating: number;
  reviewCount: number;
  inStock: boolean;
  badge?: string;
}

export interface Review {
  id: number;
  name: string;
  location: string;
  rating: number;
  date: string;
  text: string;
  verified: boolean;
}

export const allProducts: Product[] = [
  // ===== MEN'S COLLECTION =====
  {
    slug: "classic-braided-chappal",
    name: "Classic Braided Chappal",
    category: "men",
    price: 1499,
    priceUSD: 18,
    description: "Our signature Kolhapuri chappal featuring a hand-braided leather upper with a traditional toe-ring design. Crafted from premium vegetable-tanned buffalo leather that develops a beautiful patina over time. The hand-stitched sole provides superior comfort and durability, molding to the shape of your foot with every wear.",
    shortDescription: "Hand-braided leather with traditional toe-ring design",
    images: ["/images/hero-sandal.png", "/images/mens-collection.png", "/images/process-cutting.png", "/images/hero-bg.png"],
    sizes: [6, 7, 8, 9, 10, 11, 12],
    colors: [{ name: "Natural Tan", hex: "#C4956A" }, { name: "Dark Brown", hex: "#5C3A1E" }],
    style: "Traditional",
    material: "Buffalo Leather",
    artisan: "Ramesh Ji",
    artisanLocation: "Jodhpur, Rajasthan",
    artisanImage: "/images/artisan-story.png",
    rating: 4.8,
    reviewCount: 127,
    inStock: true,
    badge: "Best Seller",
  },
  {
    slug: "traditional-cross-strap",
    name: "Traditional Cross Strap",
    category: "men",
    price: 1799,
    priceUSD: 22,
    description: "A timeless cross-strap design that represents the pinnacle of Kolhapuri craftsmanship. Features interlocking leather straps that provide a secure, comfortable fit. Made with double-layered leather sole for extra cushioning on long walks.",
    shortDescription: "Interlocking cross-strap with double-layered sole",
    images: ["/images/mens-collection.png", "/images/hero-sandal.png", "/images/process-cutting.png", "/images/hero-bg.png"],
    sizes: [6, 7, 8, 9, 10, 11],
    colors: [{ name: "Cognac", hex: "#9A5B2F" }, { name: "Mahogany", hex: "#4E2B0E" }],
    style: "Cross Strap",
    material: "Buffalo Leather",
    artisan: "Suresh Ji",
    artisanLocation: "Jaisalmer, Rajasthan",
    artisanImage: "/images/artisan-story.png",
    rating: 4.7,
    reviewCount: 89,
    inStock: true,
  },
  {
    slug: "heritage-t-strap",
    name: "Heritage T-Strap",
    category: "men",
    price: 1999,
    priceUSD: 24,
    description: "Inspired by the royal Rajasthani heritage, this T-strap chappal features ornate leather work and a contoured footbed. The elevated design is perfect for festive occasions while maintaining the everyday comfort Kolhapuri Wala is known for.",
    shortDescription: "Ornate T-strap with contoured footbed for festive wear",
    images: ["/images/hero-sandal.png", "/images/mens-collection.png", "/images/hero-bg.png", "/images/process-cutting.png"],
    sizes: [7, 8, 9, 10, 11],
    colors: [{ name: "Royal Brown", hex: "#6B3F23" }, { name: "Natural Tan", hex: "#C4956A" }],
    style: "T-Strap",
    material: "Premium Goat Leather",
    artisan: "Mohan Lal Ji",
    artisanLocation: "Barmer, Rajasthan",
    artisanImage: "/images/artisan-story.png",
    rating: 4.9,
    reviewCount: 64,
    inStock: true,
    badge: "New Arrival",
  },
  {
    slug: "artisan-slide",
    name: "Artisan Slide",
    category: "men",
    price: 1299,
    priceUSD: 16,
    description: "A minimalist slide-on design that's perfect for daily wear. Simple yet elegant, this chappal showcases the beauty of pure, unadorned leather craftsmanship. Ultra-light and easy to slip on, making it ideal for quick outings.",
    shortDescription: "Minimalist slide-on for everyday comfort",
    images: ["/images/mens-collection.png", "/images/hero-sandal.png", "/images/process-cutting.png", "/images/hero-bg.png"],
    sizes: [6, 7, 8, 9, 10, 11, 12],
    colors: [{ name: "Camel", hex: "#C19A6B" }, { name: "Dark Brown", hex: "#5C3A1E" }, { name: "Black", hex: "#2C2C2C" }],
    style: "Slide",
    material: "Buffalo Leather",
    artisan: "Ramesh Ji",
    artisanLocation: "Jodhpur, Rajasthan",
    artisanImage: "/images/artisan-story.png",
    rating: 4.6,
    reviewCount: 203,
    inStock: true,
  },
  {
    slug: "rajputana-classic",
    name: "Rajputana Classic",
    category: "men",
    price: 2199,
    priceUSD: 27,
    description: "The crown jewel of our men's collection. This premium chappal features hand-carved leather motifs inspired by Rajputana architecture. Each pair takes over 3 days to craft and is truly a wearable work of art.",
    shortDescription: "Hand-carved motifs inspired by Rajputana architecture",
    images: ["/images/hero-sandal.png", "/images/mens-collection.png", "/images/process-cutting.png", "/images/artisan-story.png"],
    sizes: [7, 8, 9, 10, 11],
    colors: [{ name: "Heritage Brown", hex: "#7B4A2D" }],
    style: "Carved",
    material: "Premium Goat Leather",
    artisan: "Mohan Lal Ji",
    artisanLocation: "Barmer, Rajasthan",
    artisanImage: "/images/artisan-story.png",
    rating: 5.0,
    reviewCount: 31,
    inStock: true,
    badge: "Premium",
  },
  {
    slug: "everyday-comfort",
    name: "Everyday Comfort",
    category: "men",
    price: 999,
    priceUSD: 12,
    description: "Our most affordable Kolhapuri chappal without compromising on quality. Perfect as your first pair or as a daily beater. Simple braided design with a cushioned sole for all-day comfort.",
    shortDescription: "Affordable daily wear with cushioned sole",
    images: ["/images/mens-collection.png", "/images/hero-sandal.png", "/images/hero-bg.png", "/images/process-cutting.png"],
    sizes: [6, 7, 8, 9, 10, 11, 12],
    colors: [{ name: "Natural Tan", hex: "#C4956A" }, { name: "Brown", hex: "#8B5E3C" }],
    style: "Traditional",
    material: "Buffalo Leather",
    artisan: "Suresh Ji",
    artisanLocation: "Jaisalmer, Rajasthan",
    artisanImage: "/images/artisan-story.png",
    rating: 4.5,
    reviewCount: 312,
    inStock: true,
  },
  {
    slug: "desert-walker",
    name: "Desert Walker",
    category: "men",
    price: 1699,
    priceUSD: 21,
    description: "Built for the rugged terrains of the Thar desert, this sturdy chappal features a thick double-sole and reinforced stitching. The wider strap provides excellent foot support, making it ideal for long walks and outdoor adventures.",
    shortDescription: "Rugged double-sole design for outdoor adventures",
    images: ["/images/hero-sandal.png", "/images/mens-collection.png", "/images/process-cutting.png", "/images/hero-bg.png"],
    sizes: [7, 8, 9, 10, 11, 12],
    colors: [{ name: "Desert Tan", hex: "#B8860B" }, { name: "Dark Brown", hex: "#5C3A1E" }],
    style: "Rugged",
    material: "Double-Layer Buffalo Leather",
    artisan: "Ramesh Ji",
    artisanLocation: "Jodhpur, Rajasthan",
    artisanImage: "/images/artisan-story.png",
    rating: 4.7,
    reviewCount: 76,
    inStock: true,
  },
  {
    slug: "festive-juttis",
    name: "Festive Juttis",
    category: "men",
    price: 2499,
    priceUSD: 30,
    description: "Handcrafted leather juttis with gold thread embroidery, perfect for weddings and festive occasions. Each pair features traditional Rajasthani motifs and a cushioned insole for dancing comfort.",
    shortDescription: "Gold-embroidered juttis for weddings and celebrations",
    images: ["/images/mens-collection.png", "/images/hero-sandal.png", "/images/artisan-story.png", "/images/hero-bg.png"],
    sizes: [7, 8, 9, 10, 11],
    colors: [{ name: "Tan Gold", hex: "#DAA520" }, { name: "Maroon", hex: "#800000" }],
    style: "Jutti",
    material: "Goat Leather with Embroidery",
    artisan: "Mohan Lal Ji",
    artisanLocation: "Barmer, Rajasthan",
    artisanImage: "/images/artisan-story.png",
    rating: 4.8,
    reviewCount: 45,
    inStock: true,
    badge: "Festive",
  },

  // ===== WOMEN'S COLLECTION =====
  {
    slug: "embroidered-kolhapuri",
    name: "Embroidered Kolhapuri",
    category: "women",
    price: 1899,
    priceUSD: 23,
    description: "A stunning blend of traditional Kolhapuri craftsmanship and Rajasthani embroidery. Features hand-stitched mirror work and colorful thread patterns on premium leather. Perfect for adding a touch of artisanal elegance to any outfit.",
    shortDescription: "Mirror work and colorful thread embroidery",
    images: ["/images/womens-collection.png", "/images/hero-sandal.png", "/images/process-cutting.png", "/images/hero-bg.png"],
    sizes: [4, 5, 6, 7, 8, 9],
    colors: [{ name: "Tan with Red", hex: "#C4956A" }, { name: "Brown with Blue", hex: "#8B5E3C" }],
    style: "Embroidered",
    material: "Goat Leather with Thread Work",
    artisan: "Lakshmi Devi",
    artisanLocation: "Udaipur, Rajasthan",
    artisanImage: "/images/artisan-story.png",
    rating: 4.9,
    reviewCount: 156,
    inStock: true,
    badge: "Best Seller",
  },
  {
    slug: "beaded-t-strap",
    name: "Beaded T-Strap",
    category: "women",
    price: 2199,
    priceUSD: 27,
    description: "Elegant T-strap design adorned with hand-set glass beads and metallic accents. The delicate beadwork creates a jewel-like effect that catches the light beautifully. Perfect for festive occasions and special events.",
    shortDescription: "Hand-set glass beads with metallic accents",
    images: ["/images/womens-collection.png", "/images/hero-sandal.png", "/images/hero-bg.png", "/images/process-cutting.png"],
    sizes: [4, 5, 6, 7, 8],
    colors: [{ name: "Gold Beaded", hex: "#DAA520" }, { name: "Silver Beaded", hex: "#C0C0C0" }],
    style: "Beaded",
    material: "Goat Leather with Beadwork",
    artisan: "Lakshmi Devi",
    artisanLocation: "Udaipur, Rajasthan",
    artisanImage: "/images/artisan-story.png",
    rating: 4.8,
    reviewCount: 89,
    inStock: true,
    badge: "Premium",
  },
  {
    slug: "classic-leather-flat",
    name: "Classic Leather Flat",
    category: "women",
    price: 1599,
    priceUSD: 20,
    description: "A timeless flat chappal crafted from butter-soft goat leather. The minimal design lets the quality of the leather speak for itself. Features a cushioned insole for all-day comfort — perfect for work, travel, or casual outings.",
    shortDescription: "Butter-soft leather with cushioned insole",
    images: ["/images/womens-collection.png", "/images/hero-sandal.png", "/images/process-cutting.png", "/images/hero-bg.png"],
    sizes: [4, 5, 6, 7, 8, 9],
    colors: [{ name: "Natural Tan", hex: "#C4956A" }, { name: "Camel", hex: "#C19A6B" }, { name: "Dark Brown", hex: "#5C3A1E" }],
    style: "Flat",
    material: "Premium Goat Leather",
    artisan: "Geeta Devi",
    artisanLocation: "Jaipur, Rajasthan",
    artisanImage: "/images/artisan-story.png",
    rating: 4.7,
    reviewCount: 234,
    inStock: true,
  },
  {
    slug: "decorative-slide",
    name: "Decorative Slide",
    category: "women",
    price: 1999,
    priceUSD: 24,
    description: "A slide-on chappal featuring stunning decorative leather cutwork and brass stud accents. The wide strap provides a comfortable fit while showcasing intricate artisan detailing. A statement piece for any wardrobe.",
    shortDescription: "Leather cutwork with brass stud accents",
    images: ["/images/womens-collection.png", "/images/hero-sandal.png", "/images/hero-bg.png", "/images/process-cutting.png"],
    sizes: [5, 6, 7, 8, 9],
    colors: [{ name: "Antique Brown", hex: "#7B4A2D" }, { name: "Rose Tan", hex: "#BC8F8F" }],
    style: "Slide",
    material: "Buffalo Leather with Brass",
    artisan: "Geeta Devi",
    artisanLocation: "Jaipur, Rajasthan",
    artisanImage: "/images/artisan-story.png",
    rating: 4.6,
    reviewCount: 98,
    inStock: true,
    badge: "New Arrival",
  },
  {
    slug: "rajasthani-mojari",
    name: "Rajasthani Mojari",
    category: "women",
    price: 2499,
    priceUSD: 30,
    description: "Traditional Rajasthani mojari with exquisite hand-embroidered patterns using silk thread and tiny mirrors. The pointed toe and curved sole are hallmarks of authentic Rajasthani footwear. Perfect for weddings, festivals, and cultural events.",
    shortDescription: "Silk-embroidered mojari with mirror work",
    images: ["/images/womens-collection.png", "/images/hero-sandal.png", "/images/artisan-story.png", "/images/hero-bg.png"],
    sizes: [4, 5, 6, 7, 8],
    colors: [{ name: "Red Gold", hex: "#B22222" }, { name: "Royal Blue", hex: "#4169E1" }, { name: "Emerald", hex: "#2E8B57" }],
    style: "Mojari",
    material: "Goat Leather with Silk Embroidery",
    artisan: "Lakshmi Devi",
    artisanLocation: "Udaipur, Rajasthan",
    artisanImage: "/images/artisan-story.png",
    rating: 4.9,
    reviewCount: 67,
    inStock: true,
    badge: "Festive",
  },
  {
    slug: "bohemian-strappy",
    name: "Bohemian Strappy",
    category: "women",
    price: 1699,
    priceUSD: 21,
    description: "A free-spirited design featuring multiple thin leather straps with brass buckle closures. The bohemian-inspired look pairs perfectly with flowing skirts and summer dresses. Adjustable straps ensure a custom fit.",
    shortDescription: "Multi-strap design with brass buckle closures",
    images: ["/images/womens-collection.png", "/images/hero-sandal.png", "/images/process-cutting.png", "/images/hero-bg.png"],
    sizes: [4, 5, 6, 7, 8, 9],
    colors: [{ name: "Honey", hex: "#EB9605" }, { name: "Tan", hex: "#D2B48C" }],
    style: "Strappy",
    material: "Goat Leather with Brass",
    artisan: "Geeta Devi",
    artisanLocation: "Jaipur, Rajasthan",
    artisanImage: "/images/artisan-story.png",
    rating: 4.5,
    reviewCount: 112,
    inStock: true,
  },
  {
    slug: "minimalist-toe-ring",
    name: "Minimalist Toe Ring",
    category: "women",
    price: 1299,
    priceUSD: 16,
    description: "A delicate toe-ring chappal that embodies simplicity and elegance. The thin leather band and single toe ring create a barely-there feel while showcasing beautiful leather craftsmanship. Ideal for everyday wear.",
    shortDescription: "Delicate toe-ring design for everyday elegance",
    images: ["/images/womens-collection.png", "/images/hero-sandal.png", "/images/hero-bg.png", "/images/process-cutting.png"],
    sizes: [4, 5, 6, 7, 8, 9],
    colors: [{ name: "Natural", hex: "#C4956A" }, { name: "Blush", hex: "#DE5D83" }],
    style: "Toe Ring",
    material: "Goat Leather",
    artisan: "Lakshmi Devi",
    artisanLocation: "Udaipur, Rajasthan",
    artisanImage: "/images/artisan-story.png",
    rating: 4.4,
    reviewCount: 189,
    inStock: true,
  },
  {
    slug: "wedge-kolhapuri",
    name: "Wedge Kolhapuri",
    category: "women",
    price: 2299,
    priceUSD: 28,
    description: "A modern take on the classic Kolhapuri with a comfortable leather-wrapped wedge heel. Features traditional braided straps on a stacked leather wedge that adds 2 inches of height. Perfect for brunches and evening outings.",
    shortDescription: "Traditional braids on a 2-inch leather wedge",
    images: ["/images/womens-collection.png", "/images/hero-sandal.png", "/images/process-cutting.png", "/images/artisan-story.png"],
    sizes: [4, 5, 6, 7, 8],
    colors: [{ name: "Tan", hex: "#D2B48C" }, { name: "Dark Brown", hex: "#5C3A1E" }],
    style: "Wedge",
    material: "Buffalo Leather",
    artisan: "Geeta Devi",
    artisanLocation: "Jaipur, Rajasthan",
    artisanImage: "/images/artisan-story.png",
    rating: 4.6,
    reviewCount: 53,
    inStock: true,
  },
];

export const productReviews: Review[] = [
  { id: 1, name: "Priya Sharma", location: "Mumbai, India", rating: 5, date: "2026-03-15", text: "Absolutely love the craftsmanship! The leather is so soft and the braiding is perfect. These chappals are incredibly comfortable from day one — no breaking in needed.", verified: true },
  { id: 2, name: "James Mitchell", location: "London, UK", rating: 5, date: "2026-02-28", text: "Ordered these as a gift and was blown away. The quality is exceptional and you can see the artisan's touch in every detail. Fast international shipping too!", verified: true },
  { id: 3, name: "Ananya Patel", location: "Jaipur, India", rating: 5, date: "2026-04-02", text: "As someone from Rajasthan, I can vouch for the authenticity. These are the real deal — genuine Kolhapuri chappals with incredible craftsmanship. The leather has a gorgeous patina now after 3 months.", verified: true },
  { id: 4, name: "Sarah Chen", location: "New York, USA", rating: 4, date: "2026-01-10", text: "Beautiful sandals! The only reason I'm giving 4 stars is because the sizing runs slightly small. I'd recommend going half a size up. Otherwise, the quality is outstanding.", verified: true },
  { id: 5, name: "Vikram Joshi", location: "Delhi, India", rating: 5, date: "2026-03-22", text: "This is my third pair from Kolhapuri Wala. The durability is unmatched — my first pair is 2 years old and still going strong. The leather just gets better with age.", verified: true },
  { id: 6, name: "Emma Wilson", location: "Sydney, Australia", rating: 5, date: "2026-04-15", text: "I get compliments every time I wear these. The beadwork on the women's collection is absolutely gorgeous. You can tell they're handmade with love.", verified: true },
  { id: 7, name: "Rajesh Kumar", location: "Bangalore, India", rating: 4, date: "2026-02-05", text: "Great value for the price. The leather quality is excellent and the fit is comfortable. Would love to see more color options in future collections.", verified: true },
  { id: 8, name: "Lisa Park", location: "Toronto, Canada", rating: 5, date: "2026-03-30", text: "The sustainable packaging was a lovely surprise! Everything came in recycled kraft paper with a beautiful cotton dust bag. The sandals themselves are works of art.", verified: true },
];

export const mensProducts = allProducts.filter(p => p.category === "men");
export const womensProducts = allProducts.filter(p => p.category === "women");

export function getProductBySlug(slug: string): Product | undefined {
  return allProducts.find(p => p.slug === slug);
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return allProducts
    .filter(p => p.category === product.category && p.slug !== product.slug)
    .slice(0, limit);
}

export const styleFilters = {
  men: ["All", "Traditional", "Cross Strap", "T-Strap", "Slide", "Carved", "Rugged", "Jutti"],
  women: ["All", "Embroidered", "Beaded", "Flat", "Slide", "Mojari", "Strappy", "Toe Ring", "Wedge"],
};

export const priceRanges = [
  { label: "All Prices", min: 0, max: Infinity },
  { label: "Under ₹1,500", min: 0, max: 1499 },
  { label: "₹1,500 – ₹2,000", min: 1500, max: 2000 },
  { label: "Above ₹2,000", min: 2001, max: Infinity },
];

export const sortOptions = [
  { label: "Featured", value: "featured" },
  { label: "Price: Low to High", value: "price-asc" },
  { label: "Price: High to Low", value: "price-desc" },
  { label: "Highest Rated", value: "rating" },
  { label: "Most Reviewed", value: "reviews" },
];
